#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Message_Project
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MsgDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_message(tbl_message instance);
    partial void Updatetbl_message(tbl_message instance);
    partial void Deletetbl_message(tbl_message instance);
    partial void Inserttbl_Freind(tbl_Freind instance);
    partial void Updatetbl_Freind(tbl_Freind instance);
    partial void Deletetbl_Freind(tbl_Freind instance);
    partial void Inserttbl_Admin(tbl_Admin instance);
    partial void Updatetbl_Admin(tbl_Admin instance);
    partial void Deletetbl_Admin(tbl_Admin instance);
    partial void Inserttbl_Reply(tbl_Reply instance);
    partial void Updatetbl_Reply(tbl_Reply instance);
    partial void Deletetbl_Reply(tbl_Reply instance);
    partial void Inserttbl_Request(tbl_Request instance);
    partial void Updatetbl_Request(tbl_Request instance);
    partial void Deletetbl_Request(tbl_Request instance);
    partial void Inserttbl_user(tbl_user instance);
    partial void Updatetbl_user(tbl_user instance);
    partial void Deletetbl_user(tbl_user instance);
    partial void Inserttbl_FriendRequest(tbl_FriendRequest instance);
    partial void Updatetbl_FriendRequest(tbl_FriendRequest instance);
    partial void Deletetbl_FriendRequest(tbl_FriendRequest instance);
    partial void Inserttbl_Block(tbl_Block instance);
    partial void Updatetbl_Block(tbl_Block instance);
    partial void Deletetbl_Block(tbl_Block instance);
    partial void Inserttbl_Post(tbl_Post instance);
    partial void Updatetbl_Post(tbl_Post instance);
    partial void Deletetbl_Post(tbl_Post instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MsgDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_message> tbl_messages
		{
			get
			{
				return this.GetTable<tbl_message>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Freind> tbl_Freinds
		{
			get
			{
				return this.GetTable<tbl_Freind>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Admin> tbl_Admins
		{
			get
			{
				return this.GetTable<tbl_Admin>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Reply> tbl_Replies
		{
			get
			{
				return this.GetTable<tbl_Reply>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Request> tbl_Requests
		{
			get
			{
				return this.GetTable<tbl_Request>();
			}
		}
		
		public System.Data.Linq.Table<tbl_user> tbl_users
		{
			get
			{
				return this.GetTable<tbl_user>();
			}
		}
		
		public System.Data.Linq.Table<tbl_FriendRequest> tbl_FriendRequests
		{
			get
			{
				return this.GetTable<tbl_FriendRequest>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Block> tbl_Blocks
		{
			get
			{
				return this.GetTable<tbl_Block>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Post> tbl_Posts
		{
			get
			{
				return this.GetTable<tbl_Post>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_message")]
	public partial class tbl_message : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _msg_id;
		
		private string _msg_sender;
		
		private string _msg_recipient;
		
		private string _msg_subject;
		
		private string _msg_content;
		
		private string _date;
		
		private System.Nullable<byte> _msg_read;
		
		private System.Nullable<byte> _msg_deleted;
		
		private string _msg_status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmsg_idChanging(long value);
    partial void Onmsg_idChanged();
    partial void Onmsg_senderChanging(string value);
    partial void Onmsg_senderChanged();
    partial void Onmsg_recipientChanging(string value);
    partial void Onmsg_recipientChanged();
    partial void Onmsg_subjectChanging(string value);
    partial void Onmsg_subjectChanged();
    partial void Onmsg_contentChanging(string value);
    partial void Onmsg_contentChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void Onmsg_readChanging(System.Nullable<byte> value);
    partial void Onmsg_readChanged();
    partial void Onmsg_deletedChanging(System.Nullable<byte> value);
    partial void Onmsg_deletedChanged();
    partial void Onmsg_statusChanging(string value);
    partial void Onmsg_statusChanged();
    #endregion
		
		public tbl_message()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msg_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long msg_id
		{
			get
			{
				return this._msg_id;
			}
			set
			{
				if ((this._msg_id != value))
				{
					this.Onmsg_idChanging(value);
					this.SendPropertyChanging();
					this._msg_id = value;
					this.SendPropertyChanged("msg_id");
					this.Onmsg_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msg_sender", DbType="NVarChar(50)")]
		public string msg_sender
		{
			get
			{
				return this._msg_sender;
			}
			set
			{
				if ((this._msg_sender != value))
				{
					this.Onmsg_senderChanging(value);
					this.SendPropertyChanging();
					this._msg_sender = value;
					this.SendPropertyChanged("msg_sender");
					this.Onmsg_senderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msg_recipient", DbType="NVarChar(50)")]
		public string msg_recipient
		{
			get
			{
				return this._msg_recipient;
			}
			set
			{
				if ((this._msg_recipient != value))
				{
					this.Onmsg_recipientChanging(value);
					this.SendPropertyChanging();
					this._msg_recipient = value;
					this.SendPropertyChanged("msg_recipient");
					this.Onmsg_recipientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msg_subject", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string msg_subject
		{
			get
			{
				return this._msg_subject;
			}
			set
			{
				if ((this._msg_subject != value))
				{
					this.Onmsg_subjectChanging(value);
					this.SendPropertyChanging();
					this._msg_subject = value;
					this.SendPropertyChanged("msg_subject");
					this.Onmsg_subjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msg_content", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string msg_content
		{
			get
			{
				return this._msg_content;
			}
			set
			{
				if ((this._msg_content != value))
				{
					this.Onmsg_contentChanging(value);
					this.SendPropertyChanging();
					this._msg_content = value;
					this.SendPropertyChanged("msg_content");
					this.Onmsg_contentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(50)")]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msg_read", DbType="TinyInt")]
		public System.Nullable<byte> msg_read
		{
			get
			{
				return this._msg_read;
			}
			set
			{
				if ((this._msg_read != value))
				{
					this.Onmsg_readChanging(value);
					this.SendPropertyChanging();
					this._msg_read = value;
					this.SendPropertyChanged("msg_read");
					this.Onmsg_readChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msg_deleted", DbType="TinyInt")]
		public System.Nullable<byte> msg_deleted
		{
			get
			{
				return this._msg_deleted;
			}
			set
			{
				if ((this._msg_deleted != value))
				{
					this.Onmsg_deletedChanging(value);
					this.SendPropertyChanging();
					this._msg_deleted = value;
					this.SendPropertyChanged("msg_deleted");
					this.Onmsg_deletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msg_status", DbType="NVarChar(50)")]
		public string msg_status
		{
			get
			{
				return this._msg_status;
			}
			set
			{
				if ((this._msg_status != value))
				{
					this.Onmsg_statusChanging(value);
					this.SendPropertyChanging();
					this._msg_status = value;
					this.SendPropertyChanged("msg_status");
					this.Onmsg_statusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Freinds")]
	public partial class tbl_Freind : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FreindId;
		
		private string _CurrentUser;
		
		private string _Username;
		
		private string _Name;
		
		private string _Family;
		
		private string _Email;
		
		private string _Mobile;
		
		private string _Picture;
		
		private System.Nullable<bool> _Online;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFreindIdChanging(int value);
    partial void OnFreindIdChanged();
    partial void OnCurrentUserChanging(string value);
    partial void OnCurrentUserChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnFamilyChanging(string value);
    partial void OnFamilyChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnPictureChanging(string value);
    partial void OnPictureChanged();
    partial void OnOnlineChanging(System.Nullable<bool> value);
    partial void OnOnlineChanged();
    #endregion
		
		public tbl_Freind()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FreindId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int FreindId
		{
			get
			{
				return this._FreindId;
			}
			set
			{
				if ((this._FreindId != value))
				{
					this.OnFreindIdChanging(value);
					this.SendPropertyChanging();
					this._FreindId = value;
					this.SendPropertyChanged("FreindId");
					this.OnFreindIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentUser", DbType="NVarChar(70) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CurrentUser
		{
			get
			{
				return this._CurrentUser;
			}
			set
			{
				if ((this._CurrentUser != value))
				{
					this.OnCurrentUserChanging(value);
					this.SendPropertyChanging();
					this._CurrentUser = value;
					this.SendPropertyChanged("CurrentUser");
					this.OnCurrentUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(70)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Family", DbType="NVarChar(50)")]
		public string Family
		{
			get
			{
				return this._Family;
			}
			set
			{
				if ((this._Family != value))
				{
					this.OnFamilyChanging(value);
					this.SendPropertyChanging();
					this._Family = value;
					this.SendPropertyChanged("Family");
					this.OnFamilyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="VarChar(50)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="NVarChar(200)")]
		public string Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this.OnPictureChanging(value);
					this.SendPropertyChanging();
					this._Picture = value;
					this.SendPropertyChanged("Picture");
					this.OnPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Online", DbType="Bit")]
		public System.Nullable<bool> Online
		{
			get
			{
				return this._Online;
			}
			set
			{
				if ((this._Online != value))
				{
					this.OnOnlineChanging(value);
					this.SendPropertyChanging();
					this._Online = value;
					this.SendPropertyChanged("Online");
					this.OnOnlineChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Admin")]
	public partial class tbl_Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Username;
		
		private string _Password;
		
		private string _Name;
		
		private string _Family;
		
		private string _Email;
		
		private string _LastLogin;
		
		private string _Image;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnFamilyChanging(string value);
    partial void OnFamilyChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnLastLoginChanging(string value);
    partial void OnLastLoginChanged();
    partial void OnImageChanging(string value);
    partial void OnImageChanged();
    #endregion
		
		public tbl_Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(80)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(80)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Family", DbType="NVarChar(50)")]
		public string Family
		{
			get
			{
				return this._Family;
			}
			set
			{
				if ((this._Family != value))
				{
					this.OnFamilyChanging(value);
					this.SendPropertyChanging();
					this._Family = value;
					this.SendPropertyChanged("Family");
					this.OnFamilyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(80)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLogin", DbType="NVarChar(50)")]
		public string LastLogin
		{
			get
			{
				return this._LastLogin;
			}
			set
			{
				if ((this._LastLogin != value))
				{
					this.OnLastLoginChanging(value);
					this.SendPropertyChanging();
					this._LastLogin = value;
					this.SendPropertyChanged("LastLogin");
					this.OnLastLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="NVarChar(300)")]
		public string Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Reply")]
	public partial class tbl_Reply : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ReplyId;
		
		private string _Subject;
		
		private string _Description;
		
		private string _Reciver;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReplyIdChanging(int value);
    partial void OnReplyIdChanged();
    partial void OnSubjectChanging(string value);
    partial void OnSubjectChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnReciverChanging(string value);
    partial void OnReciverChanged();
    #endregion
		
		public tbl_Reply()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReplyId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ReplyId
		{
			get
			{
				return this._ReplyId;
			}
			set
			{
				if ((this._ReplyId != value))
				{
					this.OnReplyIdChanging(value);
					this.SendPropertyChanging();
					this._ReplyId = value;
					this.SendPropertyChanged("ReplyId");
					this.OnReplyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="NVarChar(100)")]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this.OnSubjectChanging(value);
					this.SendPropertyChanging();
					this._Subject = value;
					this.SendPropertyChanged("Subject");
					this.OnSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reciver", DbType="NVarChar(50)")]
		public string Reciver
		{
			get
			{
				return this._Reciver;
			}
			set
			{
				if ((this._Reciver != value))
				{
					this.OnReciverChanging(value);
					this.SendPropertyChanging();
					this._Reciver = value;
					this.SendPropertyChanged("Reciver");
					this.OnReciverChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Request")]
	public partial class tbl_Request : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Reqid;
		
		private string _Sender;
		
		private string _Subject;
		
		private string _Description;
		
		private string _Date;
		
		private System.Nullable<bool> _Flag;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReqidChanging(int value);
    partial void OnReqidChanged();
    partial void OnSenderChanging(string value);
    partial void OnSenderChanged();
    partial void OnSubjectChanging(string value);
    partial void OnSubjectChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnDateChanging(string value);
    partial void OnDateChanged();
    partial void OnFlagChanging(System.Nullable<bool> value);
    partial void OnFlagChanged();
    #endregion
		
		public tbl_Request()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reqid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Reqid
		{
			get
			{
				return this._Reqid;
			}
			set
			{
				if ((this._Reqid != value))
				{
					this.OnReqidChanging(value);
					this.SendPropertyChanging();
					this._Reqid = value;
					this.SendPropertyChanged("Reqid");
					this.OnReqidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sender", DbType="NVarChar(50)")]
		public string Sender
		{
			get
			{
				return this._Sender;
			}
			set
			{
				if ((this._Sender != value))
				{
					this.OnSenderChanging(value);
					this.SendPropertyChanging();
					this._Sender = value;
					this.SendPropertyChanged("Sender");
					this.OnSenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="NVarChar(100)")]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this.OnSubjectChanging(value);
					this.SendPropertyChanging();
					this._Subject = value;
					this.SendPropertyChanged("Subject");
					this.OnSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="NVarChar(50)")]
		public string Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag", DbType="Bit")]
		public System.Nullable<bool> Flag
		{
			get
			{
				return this._Flag;
			}
			set
			{
				if ((this._Flag != value))
				{
					this.OnFlagChanging(value);
					this.SendPropertyChanging();
					this._Flag = value;
					this.SendPropertyChanged("Flag");
					this.OnFlagChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_users")]
	public partial class tbl_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _User_Id;
		
		private string _Username;
		
		private string _Password;
		
		private string _Name;
		
		private string _Family;
		
		private string _Mobile;
		
		private string _Email;
		
		private string _LastLogin;
		
		private System.Data.Linq.Binary _Picture;
		
		private string _ActiveCode;
		
		private System.Nullable<bool> _ActiveMail;
		
		private System.Nullable<bool> _TwoStepValidation;
		
		private System.Nullable<bool> _Logined;
		
		private string _PicLocal;
		
		private System.Nullable<bool> _Flag;
		
		private System.Nullable<int> _CountFailedLogin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IdChanging(int value);
    partial void OnUser_IdChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnFamilyChanging(string value);
    partial void OnFamilyChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnLastLoginChanging(string value);
    partial void OnLastLoginChanged();
    partial void OnPictureChanging(System.Data.Linq.Binary value);
    partial void OnPictureChanged();
    partial void OnActiveCodeChanging(string value);
    partial void OnActiveCodeChanged();
    partial void OnActiveMailChanging(System.Nullable<bool> value);
    partial void OnActiveMailChanged();
    partial void OnTwoStepValidationChanging(System.Nullable<bool> value);
    partial void OnTwoStepValidationChanged();
    partial void OnLoginedChanging(System.Nullable<bool> value);
    partial void OnLoginedChanged();
    partial void OnPicLocalChanging(string value);
    partial void OnPicLocalChanged();
    partial void OnFlagChanging(System.Nullable<bool> value);
    partial void OnFlagChanged();
    partial void OnCountFailedLoginChanging(System.Nullable<int> value);
    partial void OnCountFailedLoginChanged();
    #endregion
		
		public tbl_user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Family", DbType="NVarChar(50)")]
		public string Family
		{
			get
			{
				return this._Family;
			}
			set
			{
				if ((this._Family != value))
				{
					this.OnFamilyChanging(value);
					this.SendPropertyChanging();
					this._Family = value;
					this.SendPropertyChanged("Family");
					this.OnFamilyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(50)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLogin", DbType="NVarChar(50)")]
		public string LastLogin
		{
			get
			{
				return this._LastLogin;
			}
			set
			{
				if ((this._LastLogin != value))
				{
					this.OnLastLoginChanging(value);
					this.SendPropertyChanging();
					this._LastLogin = value;
					this.SendPropertyChanged("LastLogin");
					this.OnLastLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this.OnPictureChanging(value);
					this.SendPropertyChanging();
					this._Picture = value;
					this.SendPropertyChanged("Picture");
					this.OnPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveCode", DbType="VarChar(50)")]
		public string ActiveCode
		{
			get
			{
				return this._ActiveCode;
			}
			set
			{
				if ((this._ActiveCode != value))
				{
					this.OnActiveCodeChanging(value);
					this.SendPropertyChanging();
					this._ActiveCode = value;
					this.SendPropertyChanged("ActiveCode");
					this.OnActiveCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveMail", DbType="Bit")]
		public System.Nullable<bool> ActiveMail
		{
			get
			{
				return this._ActiveMail;
			}
			set
			{
				if ((this._ActiveMail != value))
				{
					this.OnActiveMailChanging(value);
					this.SendPropertyChanging();
					this._ActiveMail = value;
					this.SendPropertyChanged("ActiveMail");
					this.OnActiveMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TwoStepValidation", DbType="Bit")]
		public System.Nullable<bool> TwoStepValidation
		{
			get
			{
				return this._TwoStepValidation;
			}
			set
			{
				if ((this._TwoStepValidation != value))
				{
					this.OnTwoStepValidationChanging(value);
					this.SendPropertyChanging();
					this._TwoStepValidation = value;
					this.SendPropertyChanged("TwoStepValidation");
					this.OnTwoStepValidationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logined", DbType="Bit")]
		public System.Nullable<bool> Logined
		{
			get
			{
				return this._Logined;
			}
			set
			{
				if ((this._Logined != value))
				{
					this.OnLoginedChanging(value);
					this.SendPropertyChanging();
					this._Logined = value;
					this.SendPropertyChanged("Logined");
					this.OnLoginedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicLocal", DbType="NVarChar(200)")]
		public string PicLocal
		{
			get
			{
				return this._PicLocal;
			}
			set
			{
				if ((this._PicLocal != value))
				{
					this.OnPicLocalChanging(value);
					this.SendPropertyChanging();
					this._PicLocal = value;
					this.SendPropertyChanged("PicLocal");
					this.OnPicLocalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag", DbType="Bit")]
		public System.Nullable<bool> Flag
		{
			get
			{
				return this._Flag;
			}
			set
			{
				if ((this._Flag != value))
				{
					this.OnFlagChanging(value);
					this.SendPropertyChanging();
					this._Flag = value;
					this.SendPropertyChanged("Flag");
					this.OnFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountFailedLogin", DbType="Int")]
		public System.Nullable<int> CountFailedLogin
		{
			get
			{
				return this._CountFailedLogin;
			}
			set
			{
				if ((this._CountFailedLogin != value))
				{
					this.OnCountFailedLoginChanging(value);
					this.SendPropertyChanging();
					this._CountFailedLogin = value;
					this.SendPropertyChanged("CountFailedLogin");
					this.OnCountFailedLoginChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_FriendRequest")]
	public partial class tbl_FriendRequest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FriendId;
		
		private string _CurrentUser;
		
		private string _Fusername;
		
		private string _Fname;
		
		private string _Ffamily;
		
		private string _Fmobile;
		
		private string _Femail;
		
		private string _Fpicture;
		
		private System.Nullable<bool> _DoSendRequest;
		
		private System.Nullable<bool> _Flag;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFriendIdChanging(int value);
    partial void OnFriendIdChanged();
    partial void OnCurrentUserChanging(string value);
    partial void OnCurrentUserChanged();
    partial void OnFusernameChanging(string value);
    partial void OnFusernameChanged();
    partial void OnFnameChanging(string value);
    partial void OnFnameChanged();
    partial void OnFfamilyChanging(string value);
    partial void OnFfamilyChanged();
    partial void OnFmobileChanging(string value);
    partial void OnFmobileChanged();
    partial void OnFemailChanging(string value);
    partial void OnFemailChanged();
    partial void OnFpictureChanging(string value);
    partial void OnFpictureChanged();
    partial void OnDoSendRequestChanging(System.Nullable<bool> value);
    partial void OnDoSendRequestChanged();
    partial void OnFlagChanging(System.Nullable<bool> value);
    partial void OnFlagChanged();
    #endregion
		
		public tbl_FriendRequest()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FriendId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int FriendId
		{
			get
			{
				return this._FriendId;
			}
			set
			{
				if ((this._FriendId != value))
				{
					this.OnFriendIdChanging(value);
					this.SendPropertyChanging();
					this._FriendId = value;
					this.SendPropertyChanged("FriendId");
					this.OnFriendIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentUser", DbType="VarChar(70)")]
		public string CurrentUser
		{
			get
			{
				return this._CurrentUser;
			}
			set
			{
				if ((this._CurrentUser != value))
				{
					this.OnCurrentUserChanging(value);
					this.SendPropertyChanging();
					this._CurrentUser = value;
					this.SendPropertyChanged("CurrentUser");
					this.OnCurrentUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fusername", DbType="VarChar(70)")]
		public string Fusername
		{
			get
			{
				return this._Fusername;
			}
			set
			{
				if ((this._Fusername != value))
				{
					this.OnFusernameChanging(value);
					this.SendPropertyChanging();
					this._Fusername = value;
					this.SendPropertyChanged("Fusername");
					this.OnFusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="NVarChar(50)")]
		public string Fname
		{
			get
			{
				return this._Fname;
			}
			set
			{
				if ((this._Fname != value))
				{
					this.OnFnameChanging(value);
					this.SendPropertyChanging();
					this._Fname = value;
					this.SendPropertyChanged("Fname");
					this.OnFnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ffamily", DbType="NVarChar(50)")]
		public string Ffamily
		{
			get
			{
				return this._Ffamily;
			}
			set
			{
				if ((this._Ffamily != value))
				{
					this.OnFfamilyChanging(value);
					this.SendPropertyChanging();
					this._Ffamily = value;
					this.SendPropertyChanged("Ffamily");
					this.OnFfamilyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fmobile", DbType="VarChar(50)")]
		public string Fmobile
		{
			get
			{
				return this._Fmobile;
			}
			set
			{
				if ((this._Fmobile != value))
				{
					this.OnFmobileChanging(value);
					this.SendPropertyChanging();
					this._Fmobile = value;
					this.SendPropertyChanged("Fmobile");
					this.OnFmobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Femail", DbType="VarChar(100)")]
		public string Femail
		{
			get
			{
				return this._Femail;
			}
			set
			{
				if ((this._Femail != value))
				{
					this.OnFemailChanging(value);
					this.SendPropertyChanging();
					this._Femail = value;
					this.SendPropertyChanged("Femail");
					this.OnFemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fpicture", DbType="NVarChar(MAX)")]
		public string Fpicture
		{
			get
			{
				return this._Fpicture;
			}
			set
			{
				if ((this._Fpicture != value))
				{
					this.OnFpictureChanging(value);
					this.SendPropertyChanging();
					this._Fpicture = value;
					this.SendPropertyChanged("Fpicture");
					this.OnFpictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoSendRequest", DbType="Bit")]
		public System.Nullable<bool> DoSendRequest
		{
			get
			{
				return this._DoSendRequest;
			}
			set
			{
				if ((this._DoSendRequest != value))
				{
					this.OnDoSendRequestChanging(value);
					this.SendPropertyChanging();
					this._DoSendRequest = value;
					this.SendPropertyChanged("DoSendRequest");
					this.OnDoSendRequestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag", DbType="Bit")]
		public System.Nullable<bool> Flag
		{
			get
			{
				return this._Flag;
			}
			set
			{
				if ((this._Flag != value))
				{
					this.OnFlagChanging(value);
					this.SendPropertyChanging();
					this._Flag = value;
					this.SendPropertyChanged("Flag");
					this.OnFlagChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Block")]
	public partial class tbl_Block : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserId;
		
		private string _Username;
		
		private string _UserBlock;
		
		private System.Nullable<bool> _IsBlock;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnUserBlockChanging(string value);
    partial void OnUserBlockChanged();
    partial void OnIsBlockChanging(System.Nullable<bool> value);
    partial void OnIsBlockChanged();
    #endregion
		
		public tbl_Block()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserBlock", DbType="VarChar(50)")]
		public string UserBlock
		{
			get
			{
				return this._UserBlock;
			}
			set
			{
				if ((this._UserBlock != value))
				{
					this.OnUserBlockChanging(value);
					this.SendPropertyChanging();
					this._UserBlock = value;
					this.SendPropertyChanged("UserBlock");
					this.OnUserBlockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBlock", DbType="Bit")]
		public System.Nullable<bool> IsBlock
		{
			get
			{
				return this._IsBlock;
			}
			set
			{
				if ((this._IsBlock != value))
				{
					this.OnIsBlockChanging(value);
					this.SendPropertyChanging();
					this._IsBlock = value;
					this.SendPropertyChanged("IsBlock");
					this.OnIsBlockChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Post")]
	public partial class tbl_Post : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PostId;
		
		private string _Title;
		
		private string _Content;
		
		private string _Date;
		
		private string _Publisher;
		
		private System.Nullable<bool> _State;
		
		private string _Picture;
		
		private System.Nullable<long> _Like;
		
		private System.Nullable<long> _DisLike;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPostIdChanging(int value);
    partial void OnPostIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnDateChanging(string value);
    partial void OnDateChanged();
    partial void OnPublisherChanging(string value);
    partial void OnPublisherChanged();
    partial void OnStateChanging(System.Nullable<bool> value);
    partial void OnStateChanged();
    partial void OnPictureChanging(string value);
    partial void OnPictureChanged();
    partial void OnLikeChanging(System.Nullable<long> value);
    partial void OnLikeChanged();
    partial void OnDisLikeChanging(System.Nullable<long> value);
    partial void OnDisLikeChanged();
    #endregion
		
		public tbl_Post()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PostId
		{
			get
			{
				return this._PostId;
			}
			set
			{
				if ((this._PostId != value))
				{
					this.OnPostIdChanging(value);
					this.SendPropertyChanging();
					this._PostId = value;
					this.SendPropertyChanged("PostId");
					this.OnPostIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this.OnContentChanging(value);
					this.SendPropertyChanging();
					this._Content = value;
					this.SendPropertyChanged("Content");
					this.OnContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="NVarChar(70)")]
		public string Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Publisher", DbType="VarChar(50)")]
		public string Publisher
		{
			get
			{
				return this._Publisher;
			}
			set
			{
				if ((this._Publisher != value))
				{
					this.OnPublisherChanging(value);
					this.SendPropertyChanging();
					this._Publisher = value;
					this.SendPropertyChanged("Publisher");
					this.OnPublisherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Bit")]
		public System.Nullable<bool> State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="NVarChar(100)")]
		public string Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this.OnPictureChanging(value);
					this.SendPropertyChanging();
					this._Picture = value;
					this.SendPropertyChanged("Picture");
					this.OnPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Like]", Storage="_Like", DbType="BigInt")]
		public System.Nullable<long> Like
		{
			get
			{
				return this._Like;
			}
			set
			{
				if ((this._Like != value))
				{
					this.OnLikeChanging(value);
					this.SendPropertyChanging();
					this._Like = value;
					this.SendPropertyChanged("Like");
					this.OnLikeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisLike", DbType="BigInt")]
		public System.Nullable<long> DisLike
		{
			get
			{
				return this._DisLike;
			}
			set
			{
				if ((this._DisLike != value))
				{
					this.OnDisLikeChanging(value);
					this.SendPropertyChanging();
					this._DisLike = value;
					this.SendPropertyChanged("DisLike");
					this.OnDisLikeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
